// src/lib/components/copy.svelte
<script lang="ts" module>
	type CopyState = {
		markdown: boolean;
		html: boolean;
	};
	
	let copyState = $state<CopyState>({ markdown: false, html: false });
	
	export function copyToClipboard(text: string, type: 'markdown' | 'html') {
		navigator.clipboard.writeText(text);
		copyState = { ...copyState, [type]: true };
		
		setTimeout(() => {
			copyState = { ...copyState, [type]: false };
		}, 2000);
	}
	
	export function getCopyState() {
		return copyState;
	}
</script>

<script lang="ts">
	import { Check, Copy } from 'lucide-svelte';
	
	interface Props {
		type: 'markdown' | 'html';
	}
	
	let { type }: Props = $props();
	
	const state = getCopyState();
	const isCopied = $derived(state[type]);
</script>

{#if isCopied}
	<Check class="size-4" />
{:else}
	<Copy class="size-4" />
{/if}

// components/copy.tsx
'use client'

import { useAtom } from 'jotai';
import { atomWithReducer } from 'jotai/utils'
import { CheckIcon, CopyIcon } from "lucide-react";

type CopyState = {
  markdown: boolean;
  html: boolean;
};

const copyAtom = atomWithReducer({"markdown": false, "html": false}, (state: CopyState, action: { type: keyof CopyState, to: boolean }) => {
  const { type, to } = action;
  switch (type) {
    case "markdown":
      return { ...state, markdown: to };
    case "html":
      return { ...state, html: to };
    default:
      return state;
  }
});

export const useCopy = () => {
  const [copyState, setCopyState] = useAtom(copyAtom);

  const copyToClipboard = (text: string, type: "markdown" | "html") => {
    navigator.clipboard.writeText(text);
    setCopyState({ type, to: true });

    setTimeout(() => {
      setCopyState({ type, to: false });
    }, 2000);
  };

  return { copyToClipboard, copyState };
}

export function CopyCheckIconMarkdown(){
  const { copyState } = useCopy();
  if(copyState.markdown){
    return (
      <CheckIcon className="size-4" />
    );
  }
  return <CopyIcon className="size-4" />
}

export function CopyCheckIconHTML(){
  const { copyState } = useCopy();
  if(copyState.html){
    return (
      <CheckIcon className="size-4" />
    );
  }
  return <CopyIcon className="size-4" />
}
