// src/lib/components/google-adsense.svelte
<script lang='ts'>
	import { dev } from '$app/environment';

	interface Props {
		pId: string;
	}

	const { pId }: Props = $props();
</script>

<svelte:head>
	{#if !dev && pId}
		<script async crossorigin='anonymous' src='https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-{pId}'/>
	{/if}
</svelte:head>

// components/google-adsense.tsx
import Script from "next/script";

type Props = {
	pId: string;
};

const GoogleAdsense: React.FC<Props> = ({ pId }) => {
	if (process.env.NODE_ENV !== "production") {
		return null;
	}
	return (
		<Script
			async
			src={`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-${pId}`}
			crossOrigin="anonymous"
			strategy="afterInteractive"
		/>
	);
};

export default GoogleAdsense;
