// src/lib/components/ui/input.svelte
<script lang='ts'>
	import type { HTMLInputAttributes } from 'svelte/elements';
	import { cn } from '$lib/utils.js';

	type Props = HTMLInputAttributes & {};

	let {
		class: className = undefined,
		type = 'text',
		value = $bindable(),
		...restProps
	}: Props = $props();
</script>

<input
	class={cn(
		'flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50',
		className,
	)}
	{type}
	bind:value
	{...restProps}
/>

// components/ui/input.tsx
import type * as React from "react";

import { cn } from "@/lib/utils";

const Input = ({
	ref,
	className,
	type,
	...props
}: React.ComponentProps<"input"> & {
	ref: React.RefObject<HTMLInputElement>;
}) => {
	return (
		<input
			type={type}
			className={cn(
				"flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-base ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium file:text-foreground placeholder:text-muted-foreground focus-visible:outline-hidden focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 md:text-sm",
				className,
			)}
			ref={ref}
			{...props}
		/>
	);
};
Input.displayName = "Input";

export { Input };
